In [1]:
import requests 
from bs4 import BeautifulSoup

In [2]:
website='https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops'
result=requests.get(website)
content=result.text
soup=BeautifulSoup(content,'html.parser')

In [4]:
import pandas as pd
laptops=soup.find_all('div',class_='card thumbnail')
laptop_names=[]
laptop_price=[]
for i in laptops:
    laptop_names.append(i.find('a').text.strip())
    laptop_price.append(i.find('h4').text.strip())
data={'Laptop_names':laptop_names,'Laptop_price':laptop_price}
df=pd.DataFrame(data)
df.to_csv("laptop.csv",index=False)

In [9]:
# for html web page (30 populer movies)
import requests 
from bs4 import BeautifulSoup
import pandas as pd
with open('30 Most Popular Movies.html','r',encoding='utf-8') as file:
    content=file.read()
soup=BeautifulSoup(content,'html.parser')

In [11]:
movies=soup.find_all('div',class_='article_movie_title')
movie_name=[]
movie_rating=[]
for i in movies:
    movie_name.append(i.find('a').text.strip())
    movie_rating.append(i.find('span',class_='tMeterScore').text.strip())
data={"Movie_names":movie_name,'Movie_ratings':movie_rating}
df=pd.DataFrame(data)
df

                                Movie_names Movie_ratings
0          Transformers: Rise of the Beasts           53%
1       Spider-Man: Across the Spider-Verse           96%
2                        The Little Mermaid           67%
3                             The Boogeyman           63%
4     Are You There God? It's Me, Margaret.           99%
5                                    Fast X           56%
6                                BlackBerry           98%
7                               The Machine           27%
8                                   Reality           92%
9                               Flamin' Hot           68%
10           Guardians of the Galaxy Vol. 3           82%
11                                Blue Jean           94%
12                               Past Lives           97%
13              The Super Mario Bros. Movie           58%
14                 Avatar: The Way of Water           76%
15               Guy Ritchie's The Covenant           83%
16                                Bumblebee           91%
17                                Nefarious           33%
18                                     Sisu           93%
19                     You Hurt My Feelings           95%
20                     John Wick: Chapter 4           94%
21                           Leave No Trace           80%
22                          About My Father           36%
23  Dungeons & Dragons: Honor Among Thieves           90%
24                             Transformers           57%
25                                 My Fault
26                         A Beautiful Life           50%
27     The Angry Black Girl and Her Monster           88%
28                                  Missing           87%
29                                      Air           92%

In [12]:
# fetch name,milege,price,rating from mercideze benze html file
import requests 
from bs4 import BeautifulSoup
import pandas as pd
with open('Certified used Mercedes-Benz for sale.html','r',encoding='utf-8') as file:
    content=file.read()
soup=BeautifulSoup(content,'html.parser')

In [16]:
box=soup.find_all('div',class_='vehicle-details')
name=[]
mileage=[]
price=[]
rating=[]
for i in box:
    a=i.find('h2',class_='title')
    name.append(a.text)
    b=i.find('div',class_='mileage')
    mileage.append(b.text)
    c=i.find('span',class_='primary-price')
    price.append(c.text)
    d=i.find('span',class_='sds-rating__count')
    if d:
        rating.append(d.text.strip())
    else:
        rating.append(None)
data={"Car Name":name,"Car Mileage":mileage,"Car Price":price,"Car Rating":rating}
df=pd.DataFrame(data)
df

,Car Name,Car Mileage,Car Price,Car Rating
0,2020 Mercedes-Benz CLA 250 Base 4MATIC,"28,744 mi.","$35,995",4.4
1,2019 Mercedes-Benz AMG GT 53 Base,"25,771 mi.","$79,995",4.0
2,2021 Mercedes-Benz AMG GLE 53 Base,"22,374 mi.","$80,923",2.8
3,2022 Mercedes-Benz AMG CLA 45 Base 4MATIC,"10,595 mi.","$56,633",None
4,2021 Mercedes-Benz AMG GLE 53 Base,"33,622 mi.","$76,995",4.7
5,2021 Mercedes-Benz E-Class E 450 4MATIC,"12,477 mi.","$76,532",4.5
6,2021 Mercedes-Benz AMG GLE 63 S-Model 4MATIC,"22,383 mi.","$102,990",4.8
7,2019 Mercedes-Benz S-Class S 560,"49,332 mi.","$54,580",4.8
8,2021 Mercedes-Benz AMG GLE 53 Base,"37,688 mi.","$76,715",2.8
9,2021 Mercedes-Benz GLA 250 Base,"19,521 mi.","$34,999",4.6
10,2022 Mercedes-Benz AMG C 43 Base 4MATIC,"14,420 mi.","$62,991",4.8
11,2018 Mercedes-Benz AMG C 43 Base 4MATIC,"34,555 mi.","$39,999",4.4
12,2021 Mercedes-Benz E-Class E 450 4MATIC,"16,474 mi.","$74,998",4.8
13,2021 Mercedes-Benz S-Class S 580 4MATIC,"10,233 mi.","$99,822",4.5
14,2022 Mercedes-Benz GLE 450 AWD 4MATIC,"6,800 mi.","$73,990",4.8
15,2018 Mercedes-Benz GLC 300 Base 4MATIC,"54,467 mi.","$29,151",4.5
16,2022 Mercedes-Benz AMG GLA 35 Base,"8,690 mi.","$49,736",4.5
17,2022 Mercedes-Benz GLB 250 Base,"8,158 mi.","$42,000",4.1
18,2022 Mercedes-Benz S-Class S 500 4MATIC,"8,401 mi.","$86,986",4.5
19,2020 Mercedes-Benz AMG S 63 Base 4MATIC,"24,958 mi.","$105,997",4.8
20,2021 Mercedes-Benz GLC 300 Base 4MATIC,"49,278 mi.","$37,280",4.2

In [17]:
# name,rating,discount,actual price
import requests 
from bs4 import BeautifulSoup
import pandas as pd
with open('flipkart.html','r',encoding='utf-8') as file:
    content=file.read()
soup=BeautifulSoup(content,'html.parser')

In [21]:
box=soup.find_all('div',class_='_3pLy-c row')
name=[]
d_price=[]
a_price=[]
rating=[]
for i in box:
    a=i.find('div',class_='_4rR01T')
    name.append(a.text)
    b=i.find('div',class_='_30jeq3 _1_WHN1')
    d_price.append(b.text)
    c=i.find('div',class_='_3I9_wc _27UcVY')
    # for missing actual price
    if c:
         a_price.append(c.text.strip())
    else :
        a_price.append(None)
   
    d=i.find('div',class_='_3LWZlK')
    rating.append(d.text)

data={"Mobile Name":name,"Rating":rating,"Discount Price":d_price,"Actual Price":a_price}
df=pd.DataFrame(data)
df

,Mobile Name,Rating,Discount Price,Actual Price
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,"₹39,999","₹40,999"
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,"₹39,999","₹40,999"
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,"₹49,999","₹1,01,999"
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,"₹44,999","₹95,999"
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,"₹49,999","₹74,999"
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,"₹49,999","₹74,999"
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,"₹40,999","₹45,999"
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,"₹46,999","₹47,999"
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,"₹49,999","₹1,01,999"
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,"₹47,349","₹47,999"
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,"₹38,849","₹47,999"
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,"₹44,999","₹95,999"
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,"₹49,999","₹57,990"
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,"₹47,999","₹57,990"
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,"₹48,999",None
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,"₹46,999",None
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4,"₹49,999",None
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,"₹46,999","₹48,900"
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,"₹49,999",None
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,"₹43,990","₹79,990"
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,"₹43,900","₹79,990"
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,"₹49,999","₹57,999"
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,"₹48,999","₹54,990"
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,"₹48,880","₹84,999"