In [ ]:
# this will be in ofline exam

# Geocoding api

In [13]:
import requests,json
api_key='efcee5cb18239c90db0a065fb8f11c57'
city=input("Enter Name Of City:")
# website='http://api.openweathermap.org/geo/1.0/direct?q={city name},{state code},{country code}&limit={limit}&appid={API key}'
# from open wheather 
website='http://api.openweathermap.org/geo/1.0/direct?q='+city+'&appid='+api_key
result=requests.get(website)
coordinates=result.json()
coordinates

Enter Name Of City: surat

[{'name': 'Surat',
  'local_names': {'oc': 'Surat', 'uk': 'Сюра', 'fr': 'Surat'},
  'lat': 45.9383,
  'lon': 3.2553,
  'country': 'FR',
  'state': 'Auvergne-Rhône-Alpes'}]

In [14]:
lat=coordinates[0]['lat']
lon=coordinates[0]['lon']
print(lat)
lon

45.9383

3.2553

# Current Weather

In [18]:
# current whether data api from open wheather
# https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={API key}
website='https://api.openweathermap.org/data/2.5/weather?lat='+str(lat)+'&lon='+str(lon)+'&units=metric&appid='+api_key
# str because lat and lon are float so convert into string
result=requests.get(website)
weather=result.json()
print(json.dumps(weather,indent=5))
# for proper print and indent for space
# here units=metric for temp in celcius

{
     "coord": {
          "lon": 3.2553,
          "lat": 45.9383
     },
     "weather": [
          {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
          }
     ],
     "base": "stations",
     "main": {
          "temp": 13.08,
          "feels_like": 12.74,
          "temp_min": 13.08,
          "temp_max": 13.08,
          "pressure": 1026,
          "humidity": 88,
          "sea_level": 1026,
          "grnd_level": 983
     },
     "visibility": 10000,
     "wind": {
          "speed": 0.51,
          "deg": 0
     },
     "clouds": {
          "all": 0
     },
     "dt": 1779510340,
     "sys": {
          "type": 1,
          "id": 6496,
          "country": "FR",
          "sunrise": 1779509225,
          "sunset": 1779564040
     },
     "timezone": 7200,
     "id": 2979447,
     "name": "Saint-Ignat",
     "cod": 200
}

In [20]:
dis=weather['weather'][0]['description']
vis=weather['visibility']
temp=weather['main']['temp']
hum=weather['main']['humidity']
windspeed=weather['wind']['speed']
press=weather['main']['pressure']
ccode=weather['sys']['country']
print('discription:',dis)
print('visiblity:',vis)
print('temp:',temp)
print('humidity:',hum)
print('Wind Speed:',windspeed)
print('Country Code:',ccode)
print('Pressure:',press)

discription: clear sky
visiblity: 10000
temp: 13.08
humidity: 88
Wind Speed: 0.51
Country Code: FR
Pressure: 1026

# AIr pollution

In [22]:
website='http://api.openweathermap.org/data/2.5/air_pollution?lat='+str(lat)+'&lon='+str(lon)+'&appid='+api_key
result=requests.get(website)
air=result.json()
print(json.dumps(air,indent=3))

{
   "coord": {
      "lon": 3.2553,
      "lat": 45.9383
   },
   "list": [
      {
         "main": {
            "aqi": 1
         },
         "components": {
            "co": 74.4,
            "no": 0.02,
            "no2": 2.22,
            "o3": 31.57,
            "so2": 0.09,
            "pm2_5": 2.61,
            "pm10": 3.18,
            "nh3": 27.89
         },
         "dt": 1779510847
      }
   ]
}

In [24]:
aqi=air['list'][0]['main']['aqi']
quality_indices={1:'Good',2:'Fair',3:'Moderate',4:'Poor',5:'Very Poor'}
print('current air quality=',quality_indices[aqi])

current air quality= Good

# 5 day/3 hour forecast

In [28]:
# give datframe of this data in from 5 day /3 hour forecast :date and time,temprature,pressure,humidity,discription
website='http://api.openweathermap.org/data/2.5/forecast?lat='+str(lat)+'&lon='+str(lon)+'&appid='+api_key
result=requests.get(website)
forecast=result.json()
print(json.dumps(forecast,indent=1))

{
 "cod": "200",
 "message": 0,
 "cnt": 40,
 "list": [
  {
   "dt": 1779516000,
   "main": {
    "temp": 286.23,
    "feels_like": 285.89,
    "temp_min": 286.23,
    "temp_max": 288.2,
    "pressure": 1027,
    "sea_level": 1027,
    "grnd_level": 984,
    "humidity": 88,
    "temp_kf": -1.97
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01d"
    }
   ],
   "clouds": {
    "all": 0
   },
   "wind": {
    "speed": 0.95,
    "deg": 175,
    "gust": 1.23
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-23 06:00:00"
  },
  {
   "dt": 1779526800,
   "main": {
    "temp": 289.42,
    "feels_like": 289.19,
    "temp_min": 289.42,
    "temp_max": 295.79,
    "pressure": 1027,
    "sea_level": 1027,
    "grnd_level": 984,
    "humidity": 80,
    "temp_kf": -6.37
   },
   "weather": [
    {
     "id": 801,
     "main": "Clouds",
     "description": "few clouds",
     "icon": "02d"
    }
   ],
   "clouds": {
    "all": 12
   },
   "wind": {
    "speed": 0.39,
    "deg": 72,
    "gust": 0.75
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-23 09:00:00"
  },
  {
   "dt": 1779537600,
   "main": {
    "temp": 295.73,
    "feels_like": 295.58,
    "temp_min": 295.73,
    "temp_max": 300.48,
    "pressure": 1026,
    "sea_level": 1026,
    "grnd_level": 983,
    "humidity": 59,
    "temp_kf": -4.75
   },
   "weather": [
    {
     "id": 802,
     "main": "Clouds",
     "description": "scattered clouds",
     "icon": "03d"
    }
   ],
   "clouds": {
    "all": 27
   },
   "wind": {
    "speed": 2.33,
    "deg": 338,
    "gust": 1.98
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-23 12:00:00"
  },
  {
   "dt": 1779548400,
   "main": {
    "temp": 301.52,
    "feels_like": 301.07,
    "temp_min": 301.52,
    "temp_max": 301.52,
    "pressure": 1024,
    "sea_level": 1024,
    "grnd_level": 982,
    "humidity": 39,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 802,
     "main": "Clouds",
     "description": "scattered clouds",
     "icon": "03d"
    }
   ],
   "clouds": {
    "all": 49
   },
   "wind": {
    "speed": 3.5,
    "deg": 347,
    "gust": 3.95
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-23 15:00:00"
  },
  {
   "dt": 1779559200,
   "main": {
    "temp": 299.18,
    "feels_like": 299.18,
    "temp_min": 299.18,
    "temp_max": 299.18,
    "pressure": 1024,
    "sea_level": 1024,
    "grnd_level": 982,
    "humidity": 62,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 802,
     "main": "Clouds",
     "description": "scattered clouds",
     "icon": "03d"
    }
   ],
   "clouds": {
    "all": 42
   },
   "wind": {
    "speed": 2.33,
    "deg": 359,
    "gust": 2.51
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-23 18:00:00"
  },
  {
   "dt": 1779570000,
   "main": {
    "temp": 290.71,
    "feels_like": 290.56,
    "temp_min": 290.71,
    "temp_max": 290.71,
    "pressure": 1026,
    "sea_level": 1026,
    "grnd_level": 983,
    "humidity": 78,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01n"
    }
   ],
   "clouds": {
    "all": 9
   },
   "wind": {
    "speed": 1.85,
    "deg": 325,
    "gust": 1.73
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "n"
   },
   "dt_txt": "2026-05-23 21:00:00"
  },
  {
   "dt": 1779580800,
   "main": {
    "temp": 288.26,
    "feels_like": 288.12,
    "temp_min": 288.26,
    "temp_max": 288.26,
    "pressure": 1027,
    "sea_level": 1027,
    "grnd_level": 984,
    "humidity": 88,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01n"
    }
   ],
   "clouds": {
    "all": 6
   },
   "wind": {
    "speed": 0.81,
    "deg": 306,
    "gust": 1
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "n"
   },
   "dt_txt": "2026-05-24 00:00:00"
  },
  {
   "dt": 1779591600,
   "main": {
    "temp": 286.97,
    "feels_like": 286.78,
    "temp_min": 286.97,
    "temp_max": 286.97,
    "pressure": 1027,
    "sea_level": 1027,
    "grnd_level": 984,
    "humidity": 91,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01n"
    }
   ],
   "clouds": {
    "all": 6
   },
   "wind": {
    "speed": 1.17,
    "deg": 195,
    "gust": 1.22
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "n"
   },
   "dt_txt": "2026-05-24 03:00:00"
  },
  {
   "dt": 1779602400,
   "main": {
    "temp": 290,
    "feels_like": 289.91,
    "temp_min": 290,
    "temp_max": 290,
    "pressure": 1028,
    "sea_level": 1028,
    "grnd_level": 985,
    "humidity": 83,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01d"
    }
   ],
   "clouds": {
    "all": 3
   },
   "wind": {
    "speed": 1.03,
    "deg": 163,
    "gust": 1.31
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-24 06:00:00"
  },
  {
   "dt": 1779613200,
   "main": {
    "temp": 296.71,
    "feels_like": 296.77,
    "temp_min": 296.71,
    "temp_max": 296.71,
    "pressure": 1027,
    "sea_level": 1027,
    "grnd_level": 985,
    "humidity": 63,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01d"
    }
   ],
   "clouds": {
    "all": 0
   },
   "wind": {
    "speed": 0.99,
    "deg": 35,
    "gust": 1.51
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-24 09:00:00"
  },
  {
   "dt": 1779624000,
   "main": {
    "temp": 301.77,
    "feels_like": 301.46,
    "temp_min": 301.77,
    "temp_max": 301.77,
    "pressure": 1026,
    "sea_level": 1026,
    "grnd_level": 984,
    "humidity": 41,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01d"
    }
   ],
   "clouds": {
    "all": 0
   },
   "wind": {
    "speed": 3.25,
    "deg": 0,
    "gust": 4.12
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-24 12:00:00"
  },
  {
   "dt": 1779634800,
   "main": {
    "temp": 303.1,
    "feels_like": 302.18,
    "temp_min": 303.1,
    "temp_max": 303.1,
    "pressure": 1025,
    "sea_level": 1025,
    "grnd_level": 982,
    "humidity": 34,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01d"
    }
   ],
   "clouds": {
    "all": 2
   },
   "wind": {
    "speed": 4.26,
    "deg": 30,
    "gust": 4.52
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-24 15:00:00"
  },
  {
   "dt": 1779645600,
   "main": {
    "temp": 298.32,
    "feels_like": 298.49,
    "temp_min": 298.32,
    "temp_max": 298.32,
    "pressure": 1025,
    "sea_level": 1025,
    "grnd_level": 983,
    "humidity": 61,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01d"
    }
   ],
   "clouds": {
    "all": 1
   },
   "wind": {
    "speed": 2.45,
    "deg": 60,
    "gust": 3.61
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-24 18:00:00"
  },
  {
   "dt": 1779656400,
   "main": {
    "temp": 291.82,
    "feels_like": 291.91,
    "temp_min": 291.82,
    "temp_max": 291.82,
    "pressure": 1027,
    "sea_level": 1027,
    "grnd_level": 984,
    "humidity": 83,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01n"
    }
   ],
   "clouds": {
    "all": 0
   },
   "wind": {
    "speed": 0.55,
    "deg": 353,
    "gust": 0.78
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "n"
   },
   "dt_txt": "2026-05-24 21:00:00"
  },
  {
   "dt": 1779667200,
   "main": {
    "temp": 289.87,
    "feels_like": 289.87,
    "temp_min": 289.87,
    "temp_max": 289.87,
    "pressure": 1028,
    "sea_level": 1028,
    "grnd_level": 985,
    "humidity": 87,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01n"
    }
   ],
   "clouds": {
    "all": 5
   },
   "wind": {
    "speed": 0.72,
    "deg": 206,
    "gust": 0.68
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "n"
   },
   "dt_txt": "2026-05-25 00:00:00"
  },
  {
   "dt": 1779678000,
   "main": {
    "temp": 288.56,
    "feels_like": 288.48,
    "temp_min": 288.56,
    "temp_max": 288.56,
    "pressure": 1028,
    "sea_level": 1028,
    "grnd_level": 985,
    "humidity": 89,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 801,
     "main": "Clouds",
     "description": "few clouds",
     "icon": "02n"
    }
   ],
   "clouds": {
    "all": 11
   },
   "wind": {
    "speed": 1.36,
    "deg": 201,
    "gust": 1.36
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "n"
   },
   "dt_txt": "2026-05-25 03:00:00"
  },
  {
   "dt": 1779688800,
   "main": {
    "temp": 291.25,
    "feels_like": 291.28,
    "temp_min": 291.25,
    "temp_max": 291.25,
    "pressure": 1028,
    "sea_level": 1028,
    "grnd_level": 985,
    "humidity": 83,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 801,
     "main": "Clouds",
     "description": "few clouds",
     "icon": "02d"
    }
   ],
   "clouds": {
    "all": 11
   },
   "wind": {
    "speed": 1.32,
    "deg": 181,
    "gust": 1.8
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-25 06:00:00"
  },
  {
   "dt": 1779699600,
   "main": {
    "temp": 297.63,
    "feels_like": 297.78,
    "temp_min": 297.63,
    "temp_max": 297.63,
    "pressure": 1027,
    "sea_level": 1027,
    "grnd_level": 985,
    "humidity": 63,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01d"
    }
   ],
   "clouds": {
    "all": 7
   },
   "wind": {
    "speed": 0.92,
    "deg": 103,
    "gust": 1.04
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-25 09:00:00"
  },
  {
   "dt": 1779710400,
   "main": {
    "temp": 301.99,
    "feels_like": 302.16,
    "temp_min": 301.99,
    "temp_max": 301.99,
    "pressure": 1026,
    "sea_level": 1026,
    "grnd_level": 984,
    "humidity": 46,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01d"
    }
   ],
   "clouds": {
    "all": 8
   },
   "wind": {
    "speed": 1.01,
    "deg": 353,
    "gust": 1.5
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-25 12:00:00"
  },
  {
   "dt": 1779721200,
   "main": {
    "temp": 303.67,
    "feels_like": 303.33,
    "temp_min": 303.67,
    "temp_max": 303.67,
    "pressure": 1025,
    "sea_level": 1025,
    "grnd_level": 983,
    "humidity": 39,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 801,
     "main": "Clouds",
     "description": "few clouds",
     "icon": "02d"
    }
   ],
   "clouds": {
    "all": 13
   },
   "wind": {
    "speed": 1.82,
    "deg": 3,
    "gust": 1.75
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-25 15:00:00"
  },
  {
   "dt": 1779732000,
   "main": {
    "temp": 300.41,
    "feels_like": 301.49,
    "temp_min": 300.41,
    "temp_max": 300.41,
    "pressure": 1025,
    "sea_level": 1025,
    "grnd_level": 983,
    "humidity": 59,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 802,
     "main": "Clouds",
     "description": "scattered clouds",
     "icon": "03d"
    }
   ],
   "clouds": {
    "all": 33
   },
   "wind": {
    "speed": 2.92,
    "deg": 19,
    "gust": 5.46
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-25 18:00:00"
  },
  {
   "dt": 1779742800,
   "main": {
    "temp": 293.01,
    "feels_like": 293.27,
    "temp_min": 293.01,
    "temp_max": 293.01,
    "pressure": 1027,
    "sea_level": 1027,
    "grnd_level": 985,
    "humidity": 85,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 500,
     "main": "Rain",
     "description": "light rain",
     "icon": "10n"
    }
   ],
   "clouds": {
    "all": 100
   },
   "wind": {
    "speed": 1.33,
    "deg": 165,
    "gust": 1.42
   },
   "visibility": 10000,
   "pop": 0.98,
   "rain": {
    "3h": 0.91
   },
   "sys": {
    "pod": "n"
   },
   "dt_txt": "2026-05-25 21:00:00"
  },
  {
   "dt": 1779753600,
   "main": {
    "temp": 291.15,
    "feels_like": 291.36,
    "temp_min": 291.15,
    "temp_max": 291.15,
    "pressure": 1027,
    "sea_level": 1027,
    "grnd_level": 984,
    "humidity": 90,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 500,
     "main": "Rain",
     "description": "light rain",
     "icon": "10n"
    }
   ],
   "clouds": {
    "all": 100
   },
   "wind": {
    "speed": 1.65,
    "deg": 196,
    "gust": 1.48
   },
   "visibility": 10000,
   "pop": 0.83,
   "rain": {
    "3h": 0.19
   },
   "sys": {
    "pod": "n"
   },
   "dt_txt": "2026-05-26 00:00:00"
  },
  {
   "dt": 1779764400,
   "main": {
    "temp": 289.87,
    "feels_like": 290,
    "temp_min": 289.87,
    "temp_max": 289.87,
    "pressure": 1027,
    "sea_level": 1027,
    "grnd_level": 984,
    "humidity": 92,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 804,
     "main": "Clouds",
     "description": "overcast clouds",
     "icon": "04n"
    }
   ],
   "clouds": {
    "all": 97
   },
   "wind": {
    "speed": 1.56,
    "deg": 190,
    "gust": 1.53
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "n"
   },
   "dt_txt": "2026-05-26 03:00:00"
  },
  {
   "dt": 1779775200,
   "main": {
    "temp": 292.19,
    "feels_like": 292.37,
    "temp_min": 292.19,
    "temp_max": 292.19,
    "pressure": 1027,
    "sea_level": 1027,
    "grnd_level": 984,
    "humidity": 85,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 803,
     "main": "Clouds",
     "description": "broken clouds",
     "icon": "04d"
    }
   ],
   "clouds": {
    "all": 54
   },
   "wind": {
    "speed": 1.4,
    "deg": 185,
    "gust": 1.97
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-26 06:00:00"
  },
  {
   "dt": 1779786000,
   "main": {
    "temp": 298.4,
    "feels_like": 298.57,
    "temp_min": 298.4,
    "temp_max": 298.4,
    "pressure": 1026,
    "sea_level": 1026,
    "grnd_level": 984,
    "humidity": 61,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 801,
     "main": "Clouds",
     "description": "few clouds",
     "icon": "02d"
    }
   ],
   "clouds": {
    "all": 11
   },
   "wind": {
    "speed": 1.01,
    "deg": 150,
    "gust": 1.23
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-26 09:00:00"
  },
  {
   "dt": 1779796800,
   "main": {
    "temp": 302.79,
    "feels_like": 303.26,
    "temp_min": 302.79,
    "temp_max": 302.79,
    "pressure": 1025,
    "sea_level": 1025,
    "grnd_level": 982,
    "humidity": 47,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 801,
     "main": "Clouds",
     "description": "few clouds",
     "icon": "02d"
    }
   ],
   "clouds": {
    "all": 18
   },
   "wind": {
    "speed": 1.47,
    "deg": 342,
    "gust": 1.01
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-26 12:00:00"
  },
  {
   "dt": 1779807600,
   "main": {
    "temp": 304.09,
    "feels_like": 303.46,
    "temp_min": 304.09,
    "temp_max": 304.09,
    "pressure": 1022,
    "sea_level": 1022,
    "grnd_level": 980,
    "humidity": 36,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01d"
    }
   ],
   "clouds": {
    "all": 8
   },
   "wind": {
    "speed": 3.88,
    "deg": 4,
    "gust": 3.83
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-26 15:00:00"
  },
  {
   "dt": 1779818400,
   "main": {
    "temp": 300.49,
    "feels_like": 301.27,
    "temp_min": 300.49,
    "temp_max": 300.49,
    "pressure": 1023,
    "sea_level": 1023,
    "grnd_level": 981,
    "humidity": 55,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 800,
     "main": "Clear",
     "description": "clear sky",
     "icon": "01d"
    }
   ],
   "clouds": {
    "all": 6
   },
   "wind": {
    "speed": 2.66,
    "deg": 11,
    "gust": 2.66
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-26 18:00:00"
  },
  {
   "dt": 1779829200,
   "main": {
    "temp": 292.6,
    "feels_like": 292.77,
    "temp_min": 292.6,
    "temp_max": 292.6,
    "pressure": 1025,
    "sea_level": 1025,
    "grnd_level": 982,
    "humidity": 83,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 500,
     "main": "Rain",
     "description": "light rain",
     "icon": "10n"
    }
   ],
   "clouds": {
    "all": 83
   },
   "wind": {
    "speed": 0.82,
    "deg": 277,
    "gust": 1.91
   },
   "visibility": 10000,
   "pop": 0.34,
   "rain": {
    "3h": 0.24
   },
   "sys": {
    "pod": "n"
   },
   "dt_txt": "2026-05-26 21:00:00"
  },
  {
   "dt": 1779840000,
   "main": {
    "temp": 290.97,
    "feels_like": 291.16,
    "temp_min": 290.97,
    "temp_max": 290.97,
    "pressure": 1024,
    "sea_level": 1024,
    "grnd_level": 981,
    "humidity": 90,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 804,
     "main": "Clouds",
     "description": "overcast clouds",
     "icon": "04n"
    }
   ],
   "clouds": {
    "all": 91
   },
   "wind": {
    "speed": 1.14,
    "deg": 220,
    "gust": 0.89
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "n"
   },
   "dt_txt": "2026-05-27 00:00:00"
  },
  {
   "dt": 1779850800,
   "main": {
    "temp": 289.81,
    "feels_like": 289.93,
    "temp_min": 289.81,
    "temp_max": 289.81,
    "pressure": 1023,
    "sea_level": 1023,
    "grnd_level": 980,
    "humidity": 92,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 804,
     "main": "Clouds",
     "description": "overcast clouds",
     "icon": "04n"
    }
   ],
   "clouds": {
    "all": 100
   },
   "wind": {
    "speed": 0.44,
    "deg": 198,
    "gust": 0.5
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "n"
   },
   "dt_txt": "2026-05-27 03:00:00"
  },
  {
   "dt": 1779861600,
   "main": {
    "temp": 292.07,
    "feels_like": 292.26,
    "temp_min": 292.07,
    "temp_max": 292.07,
    "pressure": 1023,
    "sea_level": 1023,
    "grnd_level": 980,
    "humidity": 86,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 804,
     "main": "Clouds",
     "description": "overcast clouds",
     "icon": "04d"
    }
   ],
   "clouds": {
    "all": 100
   },
   "wind": {
    "speed": 0.44,
    "deg": 200,
    "gust": 0.33
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },
   "dt_txt": "2026-05-27 06:00:00"
  },
  {
   "dt": 1779872400,
   "main": {
    "temp": 297.09,
    "feels_like": 297.24,
    "temp_min": 297.09,
    "temp_max": 297.09,
    "pressure": 1023,
    "sea_level": 1023,
    "grnd_level": 980,
    "humidity": 65,
    "temp_kf": 0
   },
   "weather": [
    {
     "id": 804,
     "main": "Clouds",
     "description": "overcast clouds",
     "icon": "04d"
    }
   ],
   "clouds": {
    "all": 100
   },
   "wind": {
    "speed": 2.18,
    "deg": 8,
    "gust": 2.65
   },
   "visibility": 10000,
   "pop": 0,
   "sys": {
    "pod": "d"
   },

In [34]:
import pandas as pd 
datetime=[]
temp=[]
pressure=[]
humidity=[]
description=[]
for i in forecast['list']:
    temp1=i['main']['temp']
    hum=i['main']['humidity']
    press=i['main']['pressure']
    des=i['weather'][0]['description']
    dt=i['dt_txt']
    datetime.append(dt)
    temp.append(temp1)
    humidity.append(hum)
    pressure.append(press)
    description.append(des)
data={"Date Time":datetime,"Temprature":temp,"Humidity":humidity,"Pressure":pressure,"Discription":description}
df=pd.DataFrame(data)

In [35]:
df

              Date Time  Temprature  Humidity  Pressure       Discription
0   2026-05-23 06:00:00      286.23        88      1027         clear sky
1   2026-05-23 09:00:00      289.42        80      1027        few clouds
2   2026-05-23 12:00:00      295.73        59      1026  scattered clouds
3   2026-05-23 15:00:00      301.52        39      1024  scattered clouds
4   2026-05-23 18:00:00      299.18        62      1024  scattered clouds
5   2026-05-23 21:00:00      290.71        78      1026         clear sky
6   2026-05-24 00:00:00      288.26        88      1027         clear sky
7   2026-05-24 03:00:00      286.97        91      1027         clear sky
8   2026-05-24 06:00:00      290.00        83      1028         clear sky
9   2026-05-24 09:00:00      296.71        63      1027         clear sky
10  2026-05-24 12:00:00      301.77        41      1026         clear sky
11  2026-05-24 15:00:00      303.10        34      1025         clear sky
12  2026-05-24 18:00:00      298.32        61      1025         clear sky
13  2026-05-24 21:00:00      291.82        83      1027         clear sky
14  2026-05-25 00:00:00      289.87        87      1028         clear sky
15  2026-05-25 03:00:00      288.56        89      1028        few clouds
16  2026-05-25 06:00:00      291.25        83      1028        few clouds
17  2026-05-25 09:00:00      297.63        63      1027         clear sky
18  2026-05-25 12:00:00      301.99        46      1026         clear sky
19  2026-05-25 15:00:00      303.67        39      1025        few clouds
20  2026-05-25 18:00:00      300.41        59      1025  scattered clouds
21  2026-05-25 21:00:00      293.01        85      1027        light rain
22  2026-05-26 00:00:00      291.15        90      1027        light rain
23  2026-05-26 03:00:00      289.87        92      1027   overcast clouds
24  2026-05-26 06:00:00      292.19        85      1027     broken clouds
25  2026-05-26 09:00:00      298.40        61      1026        few clouds
26  2026-05-26 12:00:00      302.79        47      1025        few clouds
27  2026-05-26 15:00:00      304.09        36      1022         clear sky
28  2026-05-26 18:00:00      300.49        55      1023         clear sky
29  2026-05-26 21:00:00      292.60        83      1025        light rain
30  2026-05-27 00:00:00      290.97        90      1024   overcast clouds
31  2026-05-27 03:00:00      289.81        92      1023   overcast clouds
32  2026-05-27 06:00:00      292.07        86      1023   overcast clouds
33  2026-05-27 09:00:00      297.09        65      1023   overcast clouds
34  2026-05-27 12:00:00      301.60        47      1021   overcast clouds
35  2026-05-27 15:00:00      302.73        37      1020   overcast clouds
36  2026-05-27 18:00:00      298.13        55      1020   overcast clouds
37  2026-05-27 21:00:00      291.37        81      1022        few clouds
38  2026-05-28 00:00:00      289.55        91      1022        few clouds
39  2026-05-28 03:00:00      287.71        93      1021         clear sky

# single posts from jason placeholder

In [3]:
import requests,json
import pandas as pd 
url='https://jsonplaceholder.typicode.com/posts/1'
response=requests.get(url)
print(response)
print(response.status_code)

<Response [200]>
200

In [5]:
print(response.text)
print(type(response.text))

{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}
<class 'str'>

In [6]:
data=response.json()
print(data)
print(type(data))

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
<class 'dict'>

In [7]:
user=data['userId']
title=data['title']
body=data['body']
print(user)
print(title)
print(body)

1
sunt aut facere repellat provident occaecati excepturi optio reprehenderit
quia et suscipit
suscipit recusandae consequuntur expedita et cum
reprehenderit molestiae ut ut quas totam
nostrum rerum est autem sunt rem eveniet architecto

# pretty json

In [9]:
formatted_json=json.dumps(data,indent=4)
print(formatted_json)

{
    "userId": 1,
    "id": 1,
    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

# get multiple post

In [10]:
url='https://jsonplaceholder.typicode.com/posts'
response=requests.get(url)
posts=response.json()
print(type(posts))
print(len(posts))
# len for number of posts

<class 'list'>
100

In [ ]:
#  fetch id and title from first 5 posts

In [13]:
url='https://jsonplaceholder.typicode.com/posts'
response=requests.get(url)
posts=response.json()

In [14]:
for post in posts[:5]:
    print(post['id'])
    print(post['title'])
    print('-'*50)

1
sunt aut facere repellat provident occaecati excepturi optio reprehenderit
--------------------------------------------------
2
qui est esse
--------------------------------------------------
3
ea molestias quasi exercitationem repellat qui ipsa sit aut
--------------------------------------------------
4
eum et est occaecati
--------------------------------------------------
5
nesciunt quas odio
--------------------------------------------------

# send query parametere

In [17]:
para={'userId':1}
url='https://jsonplaceholder.typicode.com/posts'
response=requests.get(url,params=para)
filtered_post=response.json()
print('Number of posts that have userid-1 :',len(filtered_post))

Number of posts that have userid-1 : 10

# send custom headers

In [18]:
headers={'user-Agent':"Mozilla/5.0",'Accept':'application/json'}
# ahi request send m,ozilla browser per thi thay
response=requests.get(url,headers=headers)
print(response.status_code)

200

# send Post requsts

In [19]:
url='https://jsonplaceholder.typicode.com/posts'
new_post={'Title':'Learning request','body':'this is tutorial content','userId':1}
response=requests.post(url,json=new_post)
print(response.status_code)
print(response.json())
# 201 for new creation in server but it is not change in original server

201
{'Title': 'Learning request', 'body': 'this is tutorial content', 'userId': 1, 'id': 101}

# send Put requests

In [ ]:
# for full post update put applied

In [21]:
# url='https://jsonplaceholder.typicode.com/posts - here we have to take 1st post '
url='https://jsonplaceholder.typicode.com/posts/1'
updated_post={'id':1,'title':"Updated title",'body':'updated body','userId':1}
response=requests.put(url,json=updated_post)
print(response.status_code)
print(response.json())

200
{'id': 1, 'title': 'Updated title', 'body': 'updated body', 'userId': 1}

# send Patch requests

In [23]:
# for any single parameter updation
url='https://jsonplaceholder.typicode.com/posts/1'
patch_data={'title':"Patched title"}
response=requests.patch(url,json=patch_data)
print(response.status_code)
print(response.json())

200
{'userId': 1, 'id': 1, 'title': 'Patched title', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

# send Delete requests

In [25]:
url='https://jsonplaceholder.typicode.com/posts/1'
response=requests.delete(url)
print(response.status_code)
print(response.json())

200
{}

# view response headers

In [26]:
response=requests.get('https://jsonplaceholder.typicode.com/posts/1')
print(response.headers)

{'Date': 'Tue, 26 May 2026 04:32:03 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-credentials': 'true', 'Cache-Control': 'max-age=43200', 'etag': 'W/"124-yiKdLzqO5gfBrJFrcdJ8Yq0LGnU"', 'expires': '-1', 'nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'pragma': 'no-cache', 'report-to': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=QglcSgAbDGSgTVeC%2FTtt2BgLQcIUu2Sziv5yPbSe4iM%3D\\u0026sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d\\u0026ts=1772037115"}],"max_age":3600}', 'reporting-endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=QglcSgAbDGSgTVeC%2FTtt2BgLQcIUu2Sziv5yPbSe4iM%3D&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&ts=1772037115"', 'Server': 'cloudflare', 'vary': 'Origin, Accept-Encoding', 'via': '2.0 heroku-router', 'x-content-type-options': 'nosniff', 'x-powered-by': 'Express', 'x-ratelimit-limit': '1000', 'x-ratelimit-remaining': '999', 'x-ratelimit-reset': '1772037160', 'Age': '12538', 'cf-cache-status': 'HIT', 'Content-Encoding': 'zstd', 'CF-RAY': 'a01a0dc7ea613bda-BOM', 'alt-svc': 'h3=":443"; ma=86400'}

In [27]:
print(response.headers['content-Type'])

application/json; charset=utf-8

# Download Image Using Binary Content

In [28]:
image_url='http://picsum.photos/200'
response=requests.get(image_url)
# for new binary file - wb 
with open("random_image.jpg",'wb') as f:
    f.write(response.content)

# saved json data to file

In [29]:
url='https://jsonplaceholder.typicode.com/posts/1'
response=requests.get(url)
data=response.json()
with open('post1.json','w') as f:
    json.dump(data,f,indent=4)

# read json data from file

In [31]:
with open('post1.json','r') as f:
    loaded_data=json.load(f)
print(loaded_data)

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

# convert api response to DataFrame

In [33]:
import pandas as pd
url='https://jsonplaceholder.typicode.com/posts'
response=requests.get(url)
post=response.json()
df=pd.DataFrame(post)
df.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

# convert Json String into python object

In [35]:
json_string='{"name":"alice","age":25}'
python_data=json.loads(json_string)
print(python_data)
print(type(python_data))

{'name': 'alice', 'age': 25}
<class 'dict'>

#  convert Python objct into Json string

In [37]:
person={'name':'alice','age':25}
Json_output=json.dumps(person,indent=4)
print(Json_output)

{
    "name": "alice",
    "age": 25
}

**mcq**

In [38]:
print('200= ok')
print('201= created')
print('400= bad request')
print('401= unauthorized')
print('403= forbidden')
print('404= not found')
print('500= server error')

200= ok
201= created
400= bad request
401= unauthorized
403= forbidden
404= not found
500= server error

# Token(Authorization)

In [ ]:
# token -- > one type of security key or for few pages access privately

In [39]:
import requests
url='https://jsonplaceholder.typicode.com/posts'
token='my_secret_token'
headers={"Authorization":token}
response=requests.get(url,headers=headers)
print(response.status_code)

200

# pagination

In [40]:
import requests
url='https://jsonplaceholder.typicode.com/posts'
param={'Page':1,'_limit':5}
response=requests.get(url,params=param)
data=-response.json()
print("Post ON Page 1")
for i in data:
    print(i['id'],":",i['title'])

TypeError: bad operand type for unary -: 'list'