**Geocoding API**

In [1]:
import requests,json

In [3]:
api_key="76bbb98de15cb7d16f0a7b4644071b52"
city=input("Enter the name of city:")
website="http://api.openweathermap.org/geo/1.0/direct?q="+city+"&appid="+api_key
result=requests.get(website)
coordinates=result.json()
print(coordinates)

Enter the name of city: ahmedabad

[{'name': 'Ahmedabad', 'local_names': {'or': 'ଅହମଦାବାଦ', 'ar': 'أحمد آباد', 'bn': 'আহমেদাবাদ', 'gu': 'અમદાવાદ', 'mr': 'अहमदाबाद', 'te': 'అహ్మదాబాద్', 'de': 'Ahmedabad', 'pl': 'Ahmadabad', 'cs': 'Ahmadábád', 'ur': 'احمد آباد', 'uk': 'Ахмедабад', 'zh': '艾哈迈达巴德', 'ja': 'アフマダーバード', 'ru': 'Ахмадабад', 'ta': 'அகமதாபாத்', 'hi': 'अहमदाबाद', 'kn': 'ಅಹ್ಮದಾಬಾದ್', 'ml': 'അഹമ്മദാബാദ്', 'ascii': 'Ahmedabad', 'oc': 'Ahmadabad', 'he': 'אחמדאבאד', 'pa': 'ਅਹਿਮਦਾਬਾਦ', 'tt': 'Әхмәтабад', 'eo': 'Ahmadabado', 'ne': 'अहमदाबाद', 'feature_name': 'Ahmedabad', 'en': 'Ahmedabad'}, 'lat': 23.0215374, 'lon': 72.5800568, 'country': 'IN', 'state': 'Gujarat'}]

In [6]:
Lat=coordinates[0]['lat']
Long=coordinates[0]['lon']
print("Lat=",Lat)
print('Long=',Long)

Lat= 23.0215374
Long= 72.5800568

**Current weather data**

In [12]:
website="https://api.openweathermap.org/data/2.5/weather?lat="+str(Lat)+"&lon="+str(Long)+"&units=metric&appid="+api_key
result=requests.get(website)
weather_data=result.json()
print(json.dumps(weather_data,indent=5))

{
     "coord": {
          "lon": 72.5797,
          "lat": 23.0216
     },
     "weather": [
          {
               "id": 721,
               "main": "Haze",
               "description": "haze",
               "icon": "50d"
          },
          {
               "id": 711,
               "main": "Smoke",
               "description": "smoke",
               "icon": "50d"
          }
     ],
     "base": "stations",
     "main": {
          "temp": 30.04,
          "feels_like": 32.51,
          "temp_min": 30.04,
          "temp_max": 30.04,
          "pressure": 1011,
          "humidity": 58,
          "sea_level": 1011,
          "grnd_level": 1005
     },
     "visibility": 4000,
     "wind": {
          "speed": 3.09,
          "deg": 250
     },
     "clouds": {
          "all": 20
     },
     "dt": 1779509962,
     "sys": {
          "type": 1,
          "id": 9049,
          "country": "IN",
          "sunrise": 1779495962,
          "sunset": 1779544025
     },
     "timezone": 19800,
     "id": 1279233,
     "name": "Ahmedabad",
     "cod": 200
}

In [13]:
description=weather_data['weather'][0]['description']
visibility=weather_data['visibility']
temp=weather_data['main']['temp']
pressure=weather_data['main']['pressure']
humidity=weather_data['main']['humidity']
wind_speed=weather_data['wind']['speed']
country=weather_data['sys']['country']
print("description=",description)
print("visibility=",visibility)
print("temp=",temp)
print("pressure=",pressure)
print("humidity=",humidity)
print("wind_speed=",wind_speed)
print("country=",country)

description= haze
visibility= 4000
temp= 30.04
pressure= 1011
humidity= 58
wind_speed= 3.09
country= IN

**Air Pollution**

In [14]:
website="http://api.openweathermap.org/data/2.5/air_pollution?lat="+str(Lat)+"&lon="+str(Long)+"&appid="+api_key
result=requests.get(website)
Air_pollution=result.json()
print(json.dumps(Air_pollution,indent=5))

{
     "coord": {
          "lon": 72.5801,
          "lat": 23.0215
     },
     "list": [
          {
               "main": {
                    "aqi": 1
               },
               "components": {
                    "co": 102.36,
                    "no": 0.26,
                    "no2": 1.06,
                    "o3": 53.38,
                    "so2": 1.67,
                    "pm2_5": 5.47,
                    "pm10": 13.95,
                    "nh3": 1.2
               },
               "dt": 1779510651
          }
     ]
}

In [18]:
aqi=Air_pollution['list'][0]['main']['aqi']
quality_indices={1:"Good", 2 : "Fair", 3 : 'Moderate', 4 : 'Poor', 5 : 'Very Poor'}
print("current air quality=",quality_indices[aqi])

current air quality= Good

**5 Day 3 Hour forecast**

In [19]:
website="http://api.openweathermap.org/data/2.5/forecast?lat="+str(Lat)+"&lon="+str(Long)+"&appid="+api_key
result=requests.get(website)
five_day=result.json()
print(json.dumps(five_day,indent=5))

{
     "cod": "200",
     "message": 0,
     "cnt": 40,
     "list": [
          {
               "dt": 1779516000,
               "main": {
                    "temp": 303.19,
                    "feels_like": 305.66,
                    "temp_min": 303.19,
                    "temp_max": 310.88,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 1004,
                    "humidity": 58,
                    "temp_kf": -7.69
               },
               "weather": [
                    {
                         "id": 801,
                         "main": "Clouds",
                         "description": "few clouds",
                         "icon": "02d"
                    }
               ],
               "clouds": {
                    "all": 20
               },
               "wind": {
                    "speed": 4.48,
                    "deg": 273,
                    "gust": 5.26
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 06:00:00"
          },
          {
               "dt": 1779526800,
               "main": {
                    "temp": 307.06,
                    "feels_like": 310.08,
                    "temp_min": 307.06,
                    "temp_max": 314.81,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1000,
                    "humidity": 46,
                    "temp_kf": -7.75
               },
               "weather": [
                    {
                         "id": 802,
                         "main": "Clouds",
                         "description": "scattered clouds",
                         "icon": "03d"
                    }
               ],
               "clouds": {
                    "all": 32
               },
               "wind": {
                    "speed": 5.09,
                    "deg": 267,
                    "gust": 5.94
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 09:00:00"
          },
          {
               "dt": 1779537600,
               "main": {
                    "temp": 311.05,
                    "feels_like": 313.47,
                    "temp_min": 311.05,
                    "temp_max": 314.98,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 999,
                    "humidity": 33,
                    "temp_kf": -3.93
               },
               "weather": [
                    {
                         "id": 802,
                         "main": "Clouds",
                         "description": "scattered clouds",
                         "icon": "03d"
                    }
               ],
               "clouds": {
                    "all": 48
               },
               "wind": {
                    "speed": 6.06,
                    "deg": 296,
                    "gust": 5.45
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 12:00:00"
          },
          {
               "dt": 1779548400,
               "main": {
                    "temp": 310.67,
                    "feels_like": 310.88,
                    "temp_min": 310.67,
                    "temp_max": 310.67,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 27,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 801,
                         "main": "Clouds",
                         "description": "few clouds",
                         "icon": "02n"
                    }
               ],
               "clouds": {
                    "all": 16
               },
               "wind": {
                    "speed": 3.08,
                    "deg": 251,
                    "gust": 5.76
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 15:00:00"
          },
          {
               "dt": 1779559200,
               "main": {
                    "temp": 306.61,
                    "feels_like": 308.93,
                    "temp_min": 306.61,
                    "temp_max": 306.61,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 45,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 10
               },
               "wind": {
                    "speed": 3.89,
                    "deg": 239,
                    "gust": 6.74
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 18:00:00"
          },
          {
               "dt": 1779570000,
               "main": {
                    "temp": 303.91,
                    "feels_like": 304.5,
                    "temp_min": 303.91,
                    "temp_max": 303.91,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1001,
                    "humidity": 45,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 2
               },
               "wind": {
                    "speed": 5.71,
                    "deg": 262,
                    "gust": 9.83
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 21:00:00"
          },
          {
               "dt": 1779580800,
               "main": {
                    "temp": 302.63,
                    "feels_like": 305.2,
                    "temp_min": 302.63,
                    "temp_max": 302.63,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 61,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 2
               },
               "wind": {
                    "speed": 4.7,
                    "deg": 288,
                    "gust": 8.38
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-24 00:00:00"
          },
          {
               "dt": 1779591600,
               "main": {
                    "temp": 304.77,
                    "feels_like": 307.05,
                    "temp_min": 304.77,
                    "temp_max": 304.77,
                    "pressure": 1010,
                    "sea_level": 1010,
                    "grnd_level": 1005,
                    "humidity": 51,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 1
               },
               "wind": {
                    "speed": 6.35,
                    "deg": 275,
                    "gust": 8.02
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 03:00:00"
          },
          {
               "dt": 1779602400,
               "main": {
                    "temp": 310.89,
                    "feels_like": 312.15,
                    "temp_min": 310.89,
                    "temp_max": 310.89,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 1004,
                    "humidity": 30,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 1
               },
               "wind": {
                    "speed": 5.72,
                    "deg": 265,
                    "gust": 7.05
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 06:00:00"
          },
          {
               "dt": 1779613200,
               "main": {
                    "temp": 315.22,
                    "feels_like": 315.19,
                    "temp_min": 315.22,
                    "temp_max": 315.22,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 19,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.67,
                    "deg": 275,
                    "gust": 5.66
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 09:00:00"
          },
          {
               "dt": 1779624000,
               "main": {
                    "temp": 314.79,
                    "feels_like": 313.83,
                    "temp_min": 314.79,
                    "temp_max": 314.79,
                    "pressure": 1003,
                    "sea_level": 1003,
                    "grnd_level": 998,
                    "humidity": 17,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.48,
                    "deg": 297,
                    "gust": 5.79
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 12:00:00"
          },
          {
               "dt": 1779634800,
               "main": {
                    "temp": 310.1,
                    "feels_like": 308.86,
                    "temp_min": 310.1,
                    "temp_max": 310.1,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 22,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 3.47,
                    "deg": 235,
                    "gust": 6.85
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-24 15:00:00"
          },
          {
               "dt": 1779645600,
               "main": {
                    "temp": 305.98,
                    "feels_like": 307.32,
                    "temp_min": 305.98,
                    "temp_max": 305.98,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 43,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 3.29,
                    "deg": 239,
                    "gust": 5.24
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-24 18:00:00"
          },
          {
               "dt": 1779656400,
               "main": {
                    "temp": 303.37,
                    "feels_like": 303.62,
                    "temp_min": 303.37,
                    "temp_max": 303.37,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 44,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.79,
                    "deg": 279,
                    "gust": 10.59
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-24 21:00:00"
          },
          {
               "dt": 1779667200,
               "main": {
                    "temp": 301.54,
                    "feels_like": 303.45,
                    "temp_min": 301.54,
                    "temp_max": 301.54,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1001,
                    "humidity": 62,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.84,
                    "deg": 273,
                    "gust": 9.78
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-25 00:00:00"
          },
          {
               "dt": 1779678000,
               "main": {
                    "temp": 304.49,
                    "feels_like": 305.93,
                    "temp_min": 304.49,
                    "temp_max": 304.49,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 48,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.27,
                    "deg": 266,
                    "gust": 7.18
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-25 03:00:00"
          },
          {
               "dt": 1779688800,
               "main": {
                    "temp": 311.91,
                    "feels_like": 311.34,
                    "temp_min": 311.91,
                    "temp_max": 311.91,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 22,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.21,
                    "deg": 256,
                    "gust": 6.74
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-25 06:00:00"
          },
          {
               "dt": 1779699600,
               "main": {
                    "temp": 315.93,
                    "feels_like": 314.62,
                    "temp_min": 315.93,
                    "temp_max": 315.93,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 998,
                    "humidity": 15,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.78,
                    "deg": 254,
                    "gust": 6.09
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-25 09:00:00"
          },
          {
               "dt": 1779710400,

In [20]:
date_time=[]
temp=[]
pressure=[]
humidity=[]
description=[]
for i in five_day['list']:
    date_time.append(i['dt_txt'])
    temp.append(i['main']['temp'])
    pressure.append(i['main']['pressure'])
    humidity.append(i['main']['humidity'])
    description.append(i['weather'][0]['description'])
data={'date_time':date_time,'temp':temp,'pressure':pressure,'humidity':humidity,'description':description}
import pandas as pd
df=pd.DataFrame(data)
df

              date_time    temp  pressure  humidity       description
0   2026-05-23 06:00:00  303.19      1009        58        few clouds
1   2026-05-23 09:00:00  307.06      1008        46  scattered clouds
2   2026-05-23 12:00:00  311.05      1006        33  scattered clouds
3   2026-05-23 15:00:00  310.67      1005        27        few clouds
4   2026-05-23 18:00:00  306.61      1007        45         clear sky
5   2026-05-23 21:00:00  303.91      1007        45         clear sky
6   2026-05-24 00:00:00  302.63      1008        61         clear sky
7   2026-05-24 03:00:00  304.77      1010        51         clear sky
8   2026-05-24 06:00:00  310.89      1009        30         clear sky
9   2026-05-24 09:00:00  315.22      1005        19         clear sky
10  2026-05-24 12:00:00  314.79      1003        17         clear sky
11  2026-05-24 15:00:00  310.10      1005        22         clear sky
12  2026-05-24 18:00:00  305.98      1007        43         clear sky
13  2026-05-24 21:00:00  303.37      1005        44         clear sky
14  2026-05-25 00:00:00  301.54      1007        62         clear sky
15  2026-05-25 03:00:00  304.49      1008        48         clear sky
16  2026-05-25 06:00:00  311.91      1007        22         clear sky
17  2026-05-25 09:00:00  315.93      1004        15         clear sky
18  2026-05-25 12:00:00  315.50      1002        15         clear sky
19  2026-05-25 15:00:00  309.04      1005        25         clear sky
20  2026-05-25 18:00:00  305.21      1006        37         clear sky
21  2026-05-25 21:00:00  302.82      1005        61         clear sky
22  2026-05-26 00:00:00  301.76      1006        62         clear sky
23  2026-05-26 03:00:00  304.67      1007        50         clear sky
24  2026-05-26 06:00:00  311.58      1006        25         clear sky
25  2026-05-26 09:00:00  316.09      1002        16         clear sky
26  2026-05-26 12:00:00  314.77      1001        19         clear sky
27  2026-05-26 15:00:00  307.80      1004        39         clear sky
28  2026-05-26 18:00:00  304.70      1006        50         clear sky
29  2026-05-26 21:00:00  302.81      1005        65         clear sky
30  2026-05-27 00:00:00  301.81      1006        65         clear sky
31  2026-05-27 03:00:00  304.27      1008        54         clear sky
32  2026-05-27 06:00:00  311.36      1006        27         clear sky
33  2026-05-27 09:00:00  316.19      1003        16         clear sky
34  2026-05-27 12:00:00  316.74      1001        14         clear sky
35  2026-05-27 15:00:00  305.89      1004        55         clear sky
36  2026-05-27 18:00:00  304.82      1005        58         clear sky
37  2026-05-27 21:00:00  304.20      1005        59         clear sky
38  2026-05-28 00:00:00  302.17      1006        67         clear sky
39  2026-05-28 03:00:00  304.64      1008        55         clear sky

In [2]:
import requests,json
import pandas as pd
url='https://jsonplaceholder.typicode.com/posts/1'
response=requests.get(url)
print(response)
print(response.status_code)

<Response [200]>
200

In [4]:
print(response.text)
print(type(response.text))

{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}
<class 'str'>

In [5]:
data=response.json()
print(data)
print(type(data))

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
<class 'dict'>

In [6]:
print(data['userId'])
print(data['title'])
print(data['body'])

1
sunt aut facere repellat provident occaecati excepturi optio reprehenderit
quia et suscipit
suscipit recusandae consequuntur expedita et cum
reprehenderit molestiae ut ut quas totam
nostrum rerum est autem sunt rem eveniet architecto

**pretty json format**

In [7]:
formatted_json=json.dumps(data,indent=4)
print(formatted_json)

{
    "userId": 1,
    "id": 1,
    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

**get multiple posts**

In [8]:
url='https://jsonplaceholder.typicode.com/posts'
response=requests.get(url)
posts=response.json()
print(type(posts))
print(len(posts))

<class 'list'>
100

In [9]:
for post in posts[:5]:
    print(post['id'])
    print(post['title'])
    print('-'*50)

1
sunt aut facere repellat provident occaecati excepturi optio reprehenderit
--------------------------------------------------
2
qui est esse
--------------------------------------------------
3
ea molestias quasi exercitationem repellat qui ipsa sit aut
--------------------------------------------------
4
eum et est occaecati
--------------------------------------------------
5
nesciunt quas odio
--------------------------------------------------

**send query parameter**

In [11]:
param={'userId':1}
url='https://jsonplaceholder.typicode.com/posts'
response=requests.get(url,params=param)
filtered_post=response.json()
print(len(filtered_post))

10

In [13]:
print(filtered_post)

[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}, {'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}, {'userId': 1, 'id': 4, 'title': 'eum et est occaecati', 'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'}, {'userId': 1, 'id': 5, 'title': 'nesciunt quas odio', 'body': 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque'}, {'userId': 1, 'id': 6, 'title': 'dolorem eum magni eos aperiam quia', 'body': 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae'}, {'userId': 1, 'id': 7, 'title': 'magnam facilis autem', 'body': 'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas'}, {'userId': 1, 'id': 8, 'title': 'dolorem dolore est ipsam', 'body': 'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae'}, {'userId': 1, 'id': 9, 'title': 'nesciunt iure omnis dolorem tempora et accusantium', 'body': 'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas'}, {'userId': 1, 'id': 10, 'title': 'optio molestias id quia eum', 'body': 'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error'}]

**send custom headers**

In [14]:
headers={'user-Agent':'Mozilla/5.0','Accept':'application/json'}
response=requests.get(url,headers=headers)
print(response.status_code)

200

**send POST requests**

In [15]:
url='https://jsonplaceholder.typicode.com/posts'
new_post={'title':'Learning requets','body':"this is tutorial content",'userId':1}
response=requests.post(url,json=new_post)
print(response.status_code)
print(response.json())

201
{'title': 'Learning requets', 'body': 'this is tutorial content', 'userId': 1, 'id': 101}

**send PUT requests**

In [17]:
url='https://jsonplaceholder.typicode.com/posts/1'
updated_post={'id':1,'title':'Updated title','body':'Updated body','userId':1}
response=requests.put(url,json=updated_post)
print(response.status_code)
print(response.json())

200
{'id': 1, 'title': 'Updated title', 'body': 'Updated body', 'userId': 1}

**send PATCH requsts**

In [19]:
url='https://jsonplaceholder.typicode.com/posts/1'
patch_data={'title':"Patched Title"}
response=requests.patch(url,json=patch_data)
print(response.status_code)
print(response.json())

200
{'userId': 1, 'id': 1, 'title': 'Patched Title', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

**send DELETE request**

In [22]:
url='https://jsonplaceholder.typicode.com/posts/1'
response=requests.delete(url)
print(response.status_code)

200

**view response headers**

In [23]:
response=requests.get('https://jsonplaceholder.typicode.com/posts/1')
print(response.headers)

{'Date': 'Tue, 26 May 2026 04:29:45 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-credentials': 'true', 'Cache-Control': 'max-age=43200', 'etag': 'W/"124-yiKdLzqO5gfBrJFrcdJ8Yq0LGnU"', 'expires': '-1', 'nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'pragma': 'no-cache', 'report-to': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=QglcSgAbDGSgTVeC%2FTtt2BgLQcIUu2Sziv5yPbSe4iM%3D\\u0026sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d\\u0026ts=1772037115"}],"max_age":3600}', 'reporting-endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=QglcSgAbDGSgTVeC%2FTtt2BgLQcIUu2Sziv5yPbSe4iM%3D&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&ts=1772037115"', 'Server': 'cloudflare', 'vary': 'Origin, Accept-Encoding', 'via': '2.0 heroku-router', 'x-content-type-options': 'nosniff', 'x-powered-by': 'Express', 'x-ratelimit-limit': '1000', 'x-ratelimit-remaining': '999', 'x-ratelimit-reset': '1772037160', 'Age': '12400', 'cf-cache-status': 'HIT', 'Content-Encoding': 'zstd', 'CF-RAY': 'a01a0a68dd103b28-BOM', 'alt-svc': 'h3=":443"; ma=86400'}

In [24]:
print(response.headers['Content-Type'])

application/json; charset=utf-8

**download image using binary content**

In [25]:
image_url='https://picsum.photos/200'
response=requests.get(image_url)
with open("random_image.jpg","wb") as f:
    f.write(response.content)

**saved json data to file**

In [26]:
url='https://jsonplaceholder.typicode.com/posts/1'
response=requests.get(url)
data=response.json()
with open('post1.json','w') as f:
    json.dump(data,f,indent=4)

**read json data from file**

In [27]:
with open('post1.json','r') as f:
    loaded_data=json.load(f)
print(loaded_data)

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

**convert API response to DataFrame**

In [28]:
url='https://jsonplaceholder.typicode.com/posts'
response=requests.get(url)
posts=response.json()
df=pd.DataFrame(posts)
df.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

**convert json string into python object**

In [31]:
json_string='{"name":"alice","age":25}'
python_data=json.loads(json_string)
print(python_data)
print(type(python_data))

{'name': 'alice', 'age': 25}
<class 'dict'>

**convert python object into json string**

In [32]:
person={"name":"alice","age":25}
json_output=json.dumps(person,indent=4)
print(json_output)

{
    "name": "alice",
    "age": 25
}

In [33]:
print("200= OK")
print("201= Created")
print("400= Bad requests")
print("401= Unauthorized")
print("403= Forbidden")
print("404= Not Found")
print("500= Server Error")

200= OK
201= Created
400= Bad requests
401= Unauthorized
403= Forbidden
404= Not Found
500= Server Error

**Token (Authorization)**

In [34]:
import requests
url='https://jsonplaceholder.typicode.com/posts'
token='my_secret_token'
headers={'Authorization':token}
response=requests.get(url,headers=headers)
print(response.status_code)

200

**Pagination**

In [ ]:
import requests
url='https://jsonplaceholder.typicode.com/posts'
param={"_page":1,"_limit":5}
response=requests.get(url,params=param)